# Chart values for the Camunda Platform 8 Helm chart.
# This file deliberately contains only the values that differ from the defaults.
# For changes and documentation, use your favorite diff tool to compare it with:
# https://github.com/camunda/camunda-platform-helm/blob/main/charts/camunda-platform/values.yaml

# This is a very small cluster useful for running locally and for development

global:
  image:
    tag: latest
  identity:
    auth:
      # Disable the Identity authentication
      # it will fall back to basic-auth: demo/demo as default user
      enabled: false

identity:
  enabled: false

optimize:
  enabled: false

connectors:
  enabled: true
  inbound:
    mode: disabled
  resources:
    requests:
      cpu: "100m"
      memory: "512M"
    limits:
      cpu: "1000m"
      memory: "2Gi"

zeebe:
  clusterSize: 1
  partitionCount: 1
  replicationFactor: 1
  pvcSize: 1Gi
  pvcStorageClassName: longhorn

  resources:
    requests:
      cpu: "100m"
      memory: "512M"
    limits:
      cpu: "512m"
      memory: "2Gi"

zeebe-gateway:
  replicas: 1

  resources:
    requests:
      cpu: "100m"
      memory: "512M"
    limits:
      cpu: "1000m"
      memory: "1Gi"

  logLevel: ERROR

  service:
    type: LoadBalancer
    loadBalancerIP: 192.168.2.225

elasticsearch:
  enabled: true
#  imageTag: 7.17.3
  replicas: 1
  minimumMasterNodes: 1
  # Allow no backup for single node setups
  clusterHealthCheckParams: "wait_for_status=yellow&timeout=1s"

  resources:
    requests:
      cpu: "100m"
      memory: "512M"
    limits:
      cpu: "1000m"
      memory: "2Gi"

  # Request smaller persistent volumes.
  # If you make changes to attributes below, be sure to also validate with kustomization.yaml
  # As we patch the values because of out of sync issues
  volumeClaimTemplate:
    accessModes: [ "ReadWriteOnce" ]
    storageClassName: "longhorn"
    resources:
      requests:
        storage: 15Gi

# Is part of Camunda SaaS
# See component overview: https://camunda.com/blog/2022/05/how-open-is-camunda-platform-8/
webModeler:
  enabled: false
