apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
- name: tidb-operator
  version: v1.4.5
  repo: https://charts.pingcap.org
  namespace: tidb-operator
  releaseName: tidb-operator

resources:
  - https://raw.githubusercontent.com/pingcap/tidb-operator/v1.4.5/manifests/crd.yaml
  - base/namespace.yaml
