# https://github.com/cert-manager/cert-manager/releases/download/v1.9.1/cert-manager.crds.yaml

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - name: cert-manager
    version: v1.9.1
    repo: https://charts.jetstack.io
    valuesFile: values.yaml
    namespace: cert-manager
    releaseName: cert-manager

resources:
  - base/namespace.yaml
  - base/certificates/staging/traefik-k3s-cluster-io.yaml
  - base/certificates/production/traefik-k3s-cluster-io.yaml
  - base/issuers/letsencrypt-staging.yaml
  - base/issuers/letsencrypt-production.yaml
  - base/issuers/secret-cf-token.yaml
