apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
- name: longhorn
  version: 1.4.2
  repo: https://charts.longhorn.io
  valuesFile: values.yaml
  namespace: longhorn-system
  releaseName: longhorn-system

resources:
  - base/ingress.yaml
  - base/namespace.yaml
