apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cmd-params-cm
data:
  server.insecure: "true"
  applicationsetcontroller.enable.progressive.syncs: "true"
  applicationsetcontroller.default.application.progressing.timeout: "600"
