apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- https://raw.githubusercontent.com/argoproj/argo-cd/v2.7.6/manifests/install.yaml

namespace: argocd
patches:
- path: argocd-cmd-params-cm.yaml
- path: argocd-cm.yaml
