apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
- name: traefik
  version: "v23.1.0"
  repo: https://traefik.github.io/charts
  valuesFile: values.yaml
  namespace: traefik
  releaseName: traefik

resources:
  - https://raw.githubusercontent.com/traefik/traefik/v2.10/docs/content/reference/dynamic-configuration/kubernetes-crd-definition-v1.yml
  - https://raw.githubusercontent.com/traefik/traefik/v2.10/docs/content/reference/dynamic-configuration/kubernetes-crd-rbac.yml
  - base/namespace.yaml
  - base/ingress.yaml
  - base/middleware.yaml
  - base/secret-dashboard.yaml
